name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Update system and install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git python-pip flake8 pyright fd gobject-introspection python-gobject
    
    - uses: actions/checkout@v4
        
    - name: Run flake8
      run: |
        # Find all .py files and specific extensionless scripts, then run flake8
        fd -e py -H . -x flake8
        fd 'suspendfix|WiFi-Monitor|bdp|bkb|btb' . -x flake8
      
    - name: Run pyright
      run: |
        # Find all .py files and specific extensionless scripts, then run pyright
        fd -e py -H . -x pyright
        fd 'suspendfix|WiFi-Monitor|bdp|bkb|btb' . -x pyright
